### PR TITLE
Open UDP socket only once to speed up sending

### PR DESCRIPTION
**Pull request by cdegroot**
There's no need to incur the overhead of a system call per message. UDP sockets are connectionless as @petrikero remarked in #19 so if a send fails there's something seriously wrong (more serious than you can prevent with opening sockets all the time and most likely more serious than anything you can do about it ;-)).

Having said that - it's mildly better to move opening the socket into the gen_server processing loop rather than in the init; the latter is synchronous and should be kept as fast as possible so I'm resubmitting the PR with this small change.

### CODE REVIEW

**Comment by joshuawscott** [comment]
Any possibility of getting this merged? This would greatly help us as well.

**Comment by benwilson512** [comment]
Merging. Out of curiosity, what has kept you using this library vs say something like statix?

**Comment by joshuawscott** [comment]
Inertia, I suppose? We have a dozen or so Elixir projects using this, and it would have been a bit of work to switch over 😉

**Comment by cdegroot** [comment]
(same for us - it works, we've got some wrapper code spread over a dozen Elixir projects, and with this fix, it does the job. Thanks for merging, @benwilson512!)

**Comment by benwilson512** [comment]
Understood. Plainly, this library has fallen through the cracks a bit for us, so we're trying to evaluate whether it makes sense to double down on bringing it up to date, or help folks migrate to another option. We'll keep you posted.

**Comment by cdegroot** [comment]
Or option three - hand it over to folk who do want to continue maintaining it. Not saying we would, but just completing your list of potential outcomes ;-)

**Comment by rodrigosaito** [comment]
@benwilson512 there's no release after this PR was merged. Are there any plans on releasing it?

**Pull request merged**
